apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tml-pipelines-hpa
  labels:
    app: tml-oil-gas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tml-pipelines
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
